name: Build, Test, Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: .NET Artifact
        path: Source/API/bin/Debug/net5.0
    
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: .NET Artifact
        path: Source/API/bin/Debug/net5.0
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  docker-build-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.3.0
      with:
        push: true
        tags: serodev/jobhunt:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
